service: prod

runtime: nodejs18
env: standard
instance_class: F1

# static files cache time
default_expiration: '30m'

env_variables:
  ENV: 'prod'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 50
  min_pending_latency: automatic
  max_pending_latency: automatic
